#pragma once
#include <cmath>

namespace hTsim {

// ── Physical parameters (S550 family, realistic identification — matches the
//    Gazebo sdf/hexa_s550 plant so controller allocation ≡ simulated plant) ────
constexpr double MASS     = 2.2;         // kg  (S550)
constexpr double G        = 9.81;        // m/s²
constexpr double KT       = 8.54858e-6;  // N/(rad/s)²   (fah_hexa motorConstant)
constexpr double KQ       = 1.3677728e-7;// N·m/(rad/s)² (= 0.016·KT, fah_hexa momentConstant)

// Inertia tensor (diagonal, kg·m²)
constexpr double JXX      = 0.0411;
constexpr double JYY      = 0.0478;
constexpr double JZZ      = 0.0599;

// Motor first-order time constant (s)
constexpr double TM       = 0.01;

// Motor speed limits (rad/s)
constexpr double OMEGA_MAX   = 1000.0;
constexpr double OMEGA_HOVER = 669.0;    // approx. hover per motor (√(m·g/(6·kT·cos20°)))

// Simulation and publish rates
constexpr double DT_SIM    = 0.001;      // 1 kHz dynamics
constexpr double DT_PUB    = 0.02;       // 50 Hz kinematics/viz
constexpr double CTRL_FREQ = 250.0;     // Original hardware frequency
// constexpr double CTRL_FREQ = 1000.0;    // Testing frequency
constexpr double DT_CTRL   = 1.0/CTRL_FREQ; 

// ── Motor allocation matrix M_φ (6×6) ─────────────────────────────────────────
// Rows: [f_x, f_y, f_z, τ_φ, τ_θ, τ_ψ]
// Cols: motors 1–6.  M_phi[i][j] maps Ω_j² → force/torque component i.
// Generated by scripts/validate_allocation.py directly from sdf/fah_hexa/model.sdf
// (his real S550 model: 20° cant, arm 0.27 m, kT=8.54858e-6, kQ=0.016·kT). Built from
// each rotor's quaternion-derived thrust axis + position + turningDirection, so the
// controller allocation ≡ the simulated plant. Column i == fah_hexa motorNumber i.
static constexpr double M_PHI[6][6] = {
    { 0.0000000000e+00, -2.5320738689e-06,  2.5320738357e-06,  0.0000000000e+00, -2.5320738689e-06,  2.5320738357e-06},
    {-2.9237870724e-06,  1.4618935170e-06,  1.4618935362e-06, -2.9237870724e-06,  1.4618935170e-06,  1.4618935362e-06},
    { 8.0330374116e-06,  8.0330374150e-06,  8.0330374183e-06,  8.0330374116e-06,  8.0330374150e-06,  8.0330374183e-06},
    { 0.0000000000e+00,  1.8376109657e-06,  1.8376109670e-06,  0.0000000000e+00, -1.8376109657e-06, -1.8376109670e-06},
    {-2.1221395080e-06, -1.0610697547e-06,  1.0610697549e-06,  2.1221395080e-06,  1.0610697547e-06, -1.0610697549e-06},
    {-9.1795110812e-07,  9.1788309398e-07, -9.1788308886e-07,  9.1795110812e-07, -9.1788309398e-07,  9.1788308886e-07}
};

// Precomputed inverse M_φ⁻¹ (numpy, verified M·M⁻¹=I to 3e-16)
// Rows: fah_hexa motors 0–5; cols: [f_x, f_y, f_z, τ_φ, τ_θ, τ_ψ]
static constexpr double M_PHI_INV[6][6] = {
    { 4.1760912994e-04, -1.1400739037e+05,  2.0747652143e+04,  2.5932256626e-04, -1.5707030507e+05, -1.8157274238e+05},
    {-9.8733297355e+04,  5.7003694778e+04,  2.0747652143e+04,  1.3604620571e+05, -7.8540972154e+04,  1.8157274230e+05},
    { 9.8733296896e+04,  5.7003695525e+04,  2.0747652415e+04,  1.3604620621e+05,  7.8540972098e+04, -1.8157274217e+05},
    { 4.1760912156e-04, -1.1400739037e+05,  2.0747652143e+04, -2.5932259018e-04,  1.5707030507e+05,  1.8157274238e+05},
    {-9.8733297355e+04,  5.7003694778e+04,  2.0747652143e+04, -1.3604620571e+05,  7.8540972154e+04, -1.8157274230e+05},
    { 9.8733296896e+04,  5.7003695525e+04,  2.0747652415e+04, -1.3604620621e+05, -7.8540972098e+04,  1.8157274217e+05}
};

// Derived constants
inline const double T_HOVER = MASS * G;
inline const double T_MAX   = 6.0 * M_PHI[2][0] * OMEGA_MAX * OMEGA_MAX; // z-channel only

// ── FxT Differentiator gains (Table I, FxTDiff_PD.pdf) ────────────────────────
// Applied per axis: x, y, z, φ, θ, ψ
constexpr double DIFF_G1[6]  = {5.0,  5.0,  5.0,  5.0,  5.0,  5.0};
constexpr double DIFF_G2[6]  = {6.0,  6.0, 10.0, 16.0, 16.0, 14.0};
constexpr double DIFF_Q1[6]  = {5.0,  5.0,  5.0,  5.0,  5.0,  5.0};
constexpr double DIFF_Q2[6]  = {6.0,  6.0, 10.0, 16.0, 16.0, 14.0};
constexpr double DIFF_W1     = 0.6;   // ϖ₁ ∈ (0,1)
constexpr double DIFF_RHO1   = 1.2;   // ϱ₁ > 1
constexpr double DIFF_W2     = 2.0 * DIFF_W1   - 1.0;   // = 0.2
constexpr double DIFF_RHO2   = 2.0 * DIFF_RHO1 - 1.0;   // = 1.4

// ── PD controller gains (Table I, FxTDiff_PD.pdf) ─────────────────────────────
// Applied per axis: x, y, z, φ, θ, ψ
constexpr double KP[6] = { 6.0,  6.0, 20.0, 15.0, 12.0, 20.0};
constexpr double KD[6] = { 6.0,  6.0, 10.0, 12.0, 12.0, 10.0};

} // namespace hTsim
